FROM                eb-docker:base
MAINTAINER          nadcdc4@gmail.com


ENV                 BUILD_MODE              local
ENV                 DJANGO_SETTINGS_MODULE  config.settings.${BUILD_MODE}

COPY                . /srv/project

WORKDIR             /srv/proejct/app
