# Generated by Django 2.0.7 on 2018-07-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='post')),
                ('price', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, max_length=100)),
                ('check_in', models.CharField(blank=True, max_length=100)),
                ('check_out', models.CharField(blank=True, max_length=100)),
                ('room', models.CharField(blank=True, max_length=100)),
                ('info', models.TextField(blank=True, max_length=100)),
                ('theme', models.CharField(blank=True, max_length=100)),
                ('pldx', models.IntegerField()),
            ],
        ),
    ]
